# Generated by Django 5.2.6 on 2025-09-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('mensaje', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='Resumen corto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('keywords', models.CharField(blank=True, max_length=300, verbose_name='Palabras clave')),
                ('image', models.ImageField(blank=True, null=True, upload_to='series_images/')),
                ('content_type', models.CharField(choices=[('series', 'Serie'), ('faq', 'FAQ')], default='series', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
