# Generated by Django 5.2.6 on 2025-09-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='content_type',
            field=models.CharField(choices=[('series', 'Serie')], default='series', max_length=10),
        ),
    ]
